fix mqtt
https://github.com/danielwelch/hassio-zigbee2mqtt/pull/420/commits/ed9e1a88133bb14a9e4b991c684ad397e2363876

diff --git a/teddycloud/rootfs/config.d/02_hassio-mqtt b/teddycloud/rootfs/config.d/02_hassio-mqtt
--- a/teddycloud/rootfs/config.d/02_hassio-mqtt
+++ b/teddycloud/rootfs/config.d/02_hassio-mqtt
@@ -1,10 +1,24 @@
 #!/usr/bin/env bashio
 
-set -e
+if ! bashio::services.available "mqtt"; then
+    bashio::log.info "No internal MQTT service found."
+    exit 0
+fi
 
-MQTT_HOST=$(bashio::services mqtt "host")
-MQTT_USER=$(bashio::services mqtt "username")
-MQTT_PASSWORD=$(bashio::services mqtt "password")
+
+bashio::log.info "MQTT service found, fetching server detail ..."
+if ! bashio::config.exists 'mqtt.hostname'; then
+    bashio::log.info "MQTT server not found, auto-discovering ..."
+    MQTT_HOST=$(bashio::services mqtt "host")
+    bashio::log.info "Received host: '$MQTT_HOST' for MQTT!"
+fi
+if ! bashio::config.exists 'mqtt.username'; then
+    bashio::log.info "MQTT credentials not found, auto-discovering ..."
+    MQTT_USER=$(bashio::services mqtt "username")
+    MQTT_PASSWORD=$(bashio::services mqtt "password")
+    bashio::log.info "Received user: '$MQTT_USER' for MQTT!"
+fi
+
 
 CONFIG_FILE=/teddycloud/config/config.overlay.ini
 
